In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
df = pd.read_csv('fruit_data_with_colors.txt', delimiter='\t')
df

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192,8.4,7.3,0.55
1,1,apple,granny_smith,180,8.0,6.8,0.59
2,1,apple,granny_smith,176,7.4,7.2,0.60
3,2,mandarin,mandarin,86,6.2,4.7,0.80
4,2,mandarin,mandarin,84,6.0,4.6,0.79
5,2,mandarin,mandarin,80,5.8,4.3,0.77
6,2,mandarin,mandarin,80,5.9,4.3,0.81
7,2,mandarin,mandarin,76,5.8,4.0,0.81
8,1,apple,braeburn,178,7.1,7.8,0.92
9,1,apple,braeburn,172,7.4,7.0,0.89
10,1,apple,braeburn,166,6.9,7.3,0.93
11,1,apple,braeburn,172,7.1,7.6,0.92
12,1,apple,braeburn,154,7.0,7.1,0.88
13,1,apple,golden_delicious,164,7.3,7.7,0.70
14,1,apple,golden_delicious,152,7.6,7.3,0.69
15,1,apple,golden_delicious,156,7.7,7.1,0.69
16,1,apple,golden_delicious,1000,7.6,7.5,0.67
17,1,apple,golden_delicious,168,7.5,7.6,0.73
18,1,apple,cripps_pink,162,7.5,7.1,0.83
19,1,apple,cripps_pink,162,7.4,7.2,0.85
20,1,apple,cripps_pink,160,7.5,7.5,0.86
21,1,apple,cripps_pink,156,7.4,7.4,0.84
22,1,apple,cripps_pink,140,7.3,7.1,0.87
23,1,apple,cripps_pink,170,7.6,7.9,0.88
24,3,orange,spanish_jumbo,342,9.0,9.4,0.75
25,3,orange,spanish_jumbo,356,9.2,9.2,0.75
26,3,orange,spanish_jumbo,362,9.6,9.2,0.74
27,3,orange,selected_seconds,204,7.5,9.2,0.77
28,3,orange,selected_seconds,140,6.7,7.1,0.72
29,3,orange,selected_seconds,160,7.0,7.4,0.81
30,3,orange,selected_seconds,158,7.1,7.5,0.79
31,3,orange,selected_seconds,210,7.8,8.0,0.82
32,3,orange,selected_seconds,164,7.2,7.0,0.80
33,3,orange,turkey_navel,190,7.5,8.1,0.74
34,3,orange,turkey_navel,142,7.6,7.8,0.75
35,3,orange,turkey_navel,150,7.1,7.9,0.75
36,3,orange,turkey_navel,160,7.1,7.6,0.76
37,3,orange,turkey_navel,154,7.3,7.3,0.79
38,3,orange,turkey_navel,158,7.2,7.8,0.77
39,3,orange,turkey_navel,154,7.3,7.5,0.76
40,3,orange,turkey_navel,30000,7.1,7.5,0.78
41,3,orange,turkey_navel,180,7.6,8.2,0.79
42,3,orange,turkey_navel,154,7.2,7.2,0.82
43,4,lemon,spanish_belsan,194,7.2,10.3,0.70
44,4,lemon,spanish_belsan,200,7.3,10.5,0.72
45,4,lemon,spanish_belsan,186,7.2,9.2,0.72
46,4,lemon,spanish_belsan,216,7.3,10.2,0.71
47,4,lemon,spanish_belsan,196,7.3,9.7,0.72
48,4,lemon,spanish_belsan,174,7.3,10.1,0.72
49,4,lemon,unknown,132,5.8,8.7,0.73
50,4,lemon,unknown,130,6.0,8.2,0.71
51,4,lemon,unknown,116,6.0,7.5,0.72
52,4,lemon,unknown,118,5.9,8.0,0.72
53,4,lemon,unknown,120,6.0,8.4,0.74
54,4,lemon,unknown,116,6.1,8.5,0.71
55,4,lemon,unknown,116,6.3,7.7,0.72
56,4,lemon,unknown,116,5.9,8.1,0.73
57,4,lemon,unknown,152,6.5,8.5,0.72
58,4,lemon,unknown,118,6.1,8.1,0.70

In [3]:
df.head()

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [4]:
# query_instance=np.array([180,8.0,6.8,0.59])
# mass	width	height	color_score
# w,x,y,z
#mass-x

X=df[['mass','width','height','color_score']]
Y=df['fruit_label']

# num_arr=np.array(df[['mass','width','height','color_score']])
# df.iloc[:50]

trainX=np.array(X[:50])
trainY=np.array(Y[:50])

testX=np.array(X[50:])
testY=np.array(Y[50:])

trainX[0]

array([192.  ,   8.4 ,   7.3 ,   0.55])

In [69]:
class KNN:
    def __init__(self,k=1):
        self.k = k
        
    def euclidian_dist(self,target_query,X):
        
        sq_point_dist=np.square((np.array(X)-np.array(target_query)))
        sum_of_sq=np.sum(sq_point_dist, axis=1)
        distance=np.sqrt(sum_of_sq)
        return distance
    
    def nearest_neighbours(self,distance):
        
        return np.argsort(distance)[:self.k]
                
    def predict(self,query,trainX,trainY):
        ed=self.euclidian_dist(query,trainX)
        nn=self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count)

In [70]:
classifier = KNN(3)
predictions = [classifier.predict(x,trainX,trainY) for x in testX]
predictions
#---- 9 instances so 9 lables for each instance it will pick K distance lables of min dis---#

[4, 4, 4, 4, 4, 4, 4, 3, 4]

In [71]:
#confusion matrix , performance_accuracy skitlearn
from sklearn.metrics import accuracy_score

In [72]:
accuracy_score(predictions,testY)

0.8888888888888888

In [73]:
from sklearn.metrics import confusion_matrix

In [74]:
confusion_matrix(testY,predictions)

array([[0, 0],
       [1, 8]])

In [75]:
for i in range (1,6):
    print('\n')
    print('K value = ',i)
    classifier = KNN(i)
    predictions = [classifier.predict(x,trainX,trainY) for x in testX]
    print(predictions)
    
    print('Accuracy Score',accuracy_score(predictions,testY))
    print('Confusion Matrix',confusion_matrix(testY,predictions))

K value =  1
[4, 4, 4, 4, 4, 4, 4, 1, 4]
Accuracy Score 0.8888888888888888
Confusion Matrix [[0 0]
 [1 8]]


K value =  2
[4, 4, 4, 4, 4, 4, 4, 1, 4]
Accuracy Score 0.8888888888888888
Confusion Matrix [[0 0]
 [1 8]]


K value =  3
[4, 4, 4, 4, 4, 4, 4, 3, 4]
Accuracy Score 0.8888888888888888
Confusion Matrix [[0 0]
 [1 8]]


K value =  4
[3, 3, 3, 3, 3, 3, 3, 3, 3]
Accuracy Score 0.0
Confusion Matrix [[0 0]
 [9 0]]


K value =  5
[3, 3, 3, 3, 3, 3, 3, 3, 3]
Accuracy Score 0.0
Confusion Matrix [[0 0]
 [9 0]]