In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

In [3]:
df.head()

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [4]:
X = df[["mass","width","height"]]
X

     mass  width  height
0     192    8.4     7.3
1     180    8.0     6.8
2     176    7.4     7.2
3      86    6.2     4.7
4      84    6.0     4.6
5      80    5.8     4.3
6      80    5.9     4.3
7      76    5.8     4.0
8     178    7.1     7.8
9     172    7.4     7.0
10    166    6.9     7.3
11    172    7.1     7.6
12    154    7.0     7.1
13    164    7.3     7.7
14    152    7.6     7.3
15    156    7.7     7.1
16   1000    7.6     7.5
17    168    7.5     7.6
18    162    7.5     7.1
19    162    7.4     7.2
20    160    7.5     7.5
21    156    7.4     7.4
22    140    7.3     7.1
23    170    7.6     7.9
24    342    9.0     9.4
25    356    9.2     9.2
26    362    9.6     9.2
27    204    7.5     9.2
28    140    6.7     7.1
29    160    7.0     7.4
30    158    7.1     7.5
31    210    7.8     8.0
32    164    7.2     7.0
33    190    7.5     8.1
34    142    7.6     7.8
35    150    7.1     7.9
36    160    7.1     7.6
37    154    7.3     7.3
38    158    7.2     7.8
39    154    7.3     7.5
40  30000    7.1     7.5
41    180    7.6     8.2
42    154    7.2     7.2
43    194    7.2    10.3
44    200    7.3    10.5
45    186    7.2     9.2
46    216    7.3    10.2
47    196    7.3     9.7
48    174    7.3    10.1
49    132    5.8     8.7
50    130    6.0     8.2
51    116    6.0     7.5
52    118    5.9     8.0
53    120    6.0     8.4
54    116    6.1     8.5
55    116    6.3     7.7
56    116    5.9     8.1
57    152    6.5     8.5
58    118    6.1     8.1

In [5]:
Y = df["fruit_label"]

In [8]:
trainX = np.array(X[:51])
trainY = np.array(Y[:51])
testX = np.array(X[51:])
testY = np.array(Y[51:])

In [9]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count)

In [10]:
classifier = KNN(3)

In [11]:
predictions = [classifier.predict(x,trainX,trainY) for x in testX]

In [12]:
predictions

[4, 4, 4, 4, 4, 4, 3, 4]

In [14]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4])

In [12]:
if __name__ == "__main__":
    print("hello")

hello